const WALLET_PUBLIC_ADDR = "1BhC5AgogaeNfqmaonKJwGQxaHMK8wHSsA";
const List<String> SUPPORTED_PAIRS = ['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'YFIUSDT',
  'XRPUSDT', 'ADAUSDT', 'LINKUSDT', 'SUSHIUSDT', 'UNIUSDT', 'DOTUSDT'];
const EXPORT_CSV_FILENAME = 'export.csv';